<?php 
//------------------------------------------------------------------------------
//<INFO >
//     This file was generated by MyPhpGuard 1.2.5.15475
//     
//     Date:2/26/2015 12:56:23 PM
//
// </INFO >
//------------------------------------------------------------------------------
 /**
 * 
 * @category    
 * @package    
 * @author      
 * @copyright    
 * @license     
 * @version    
 * @link   
 *      
 */
?>
<?php
$mystr1s2235 = "\x6c\x6f\x63a\x6c\x68\x6fs\x74";$mystr1s2236 = "\x72\x6f\x6ft";$mystr1s2237 = "";$mystr1s2238 = mysql_connect($mystr1s2235, $mystr1s2236, $mystr1s2237);
if (!$mystr1s2238) {die("\x43\x6f\x6en\x65\x63\x74i\x6f\x6e\x20\x66a\x69\x6c\x65d\x3a\x20" . mysql_error());
}$mystr1s2239 = mysql_select_db('work', $mystr1s2238);if (!$mystr1s2239) {die ('Connection failed : ' . mysql_error());
}
