<?php 
//------------------------------------------------------------------------------
//<INFO >
//     This file was generated by MyPhpGuard 1.2.5.15475
//     
//     Date:2/26/2015 12:56:23 PM
//
// </INFO >
//------------------------------------------------------------------------------
 /**
 * 
 * @category    
 * @package    
 * @author      
 * @copyright    
 * @license     
 * @version    
 * @link   
 *      
 */
?>
<?php
echo "\x3c\x62>S\x55\x42\x4dI\x54\x20\x44\x45T\x41\x49\x4c<\x2f\x62><\x62\x72/>\x3c\x62\x72\x2f>";
?>
<html>
<head>
</head>
<body>
<form method="post" action="/form.php">
<table>
<tr>
<td>Name:</td>
<td> <input type="text" name="name" required="required" placeholder="FULL NAME" /> </td>
</tr>
<tr>
<td>Email:</td>
<td><input type="email" name="email" required="required" placeholder="EMAIL ADDRESS" /> </td>
</tr>
<tr>
<td><input type="submit" value="submit" /></td>
</tr>
</table>
</form>
<br/>
<br/>
<a href="/detail.php">Detail</a>
</body>
</html>
